version: "3.8"
services:
  app:
    build: .
    image: nhakobyan685/flaskenvdev:v0.1.0
    volumes:
      - .:/app:rw
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=dev
