name: Docker Image CI

on: push
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker-compose -f docker-compose-prod.yml up --build -y 
        docker -compose-f docker-compose.yml up --build -y
    - name: Login in Docker hub
      uses: docker/login-action@v1
      with:
        username: nhakobyan685                  
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push to Docker hub
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: nhakobyan685/envflaskprod:v0.1.0, nhakobyan685/envflaskprod:${{ github.run_number }} 
