name: Docker Image CI

on: push
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose -f docker-compose-prod.yml up --build -y
    - name: Push image in Dockerhub
      run : |
       docker login -u nhakobyan685 -p ${{ secrets.DOCKER_TOKEN }} 
       docker image push nhakobyan685/flaskenvprod:v0.1.0
        docker image push nhakobyan685/flaskenvdev:v0.1.0
